added roll back workflow

diff --git a/.github/workflows/promote-prod.yaml b/.github/workflows/promote-prod.yaml
--- a/.github/workflows/promote-prod.yaml
+++ b/.github/workflows/promote-prod.yaml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
     inputs:
       confirmation:
-        description: Type PROMOTE to confirm Promoting the cadidate image to Production
+        description: Type PROMOTE to confirm promotion to Production
         required: true
         type: string
 
@@ -17,11 +17,23 @@ env:
   AWS_REGION: ${{ vars.AWS_REGION }}
     
 jobs:
+  confirm-promotion:
+    name: Confirm Production Promotion
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate confirmation
+        if: inputs.confirmation != 'PROMOTE'
+        run: |
+          echo "Invalid confirmation."
+          echo "You must type PROMOTE to continue."
+          exit 1
+
   # Resolve the candidate image tag and digest from paramstore
   # The Job has an internal validation logic, which will be run against the image on the dev ECR repo, 
   # before copying it to the prod ECR repo. This is to ensure consistency.
   resolve-image:
     name: Resolve Candidate Image
+    needs: confirm-promotion
     uses: SparrowX-ECS/workflows-templates/.github/workflows/resolve-image.yaml@v4.3.0
     with:
       ssm-parameter-path: ${{ vars.PROD_CANDIDATE_PARAM_STORE_PATH }}
